import { describe, expect, it } from "vitest";
process.env.DATABASE_URL ||= "postgresql://test:test@localhost:5432/test";
import { normalizeVscoEvent } from "@/providers/vsco";
import { deterministicIntent, isFinancialQuestion, standardPayReply } from "@/services/inbound";
import { nextAllowedTime, outsideQuietHours } from "@/lib/quiet-hours";
import { createOpaqueToken, sha256, verifyHmac, verifyQuoWebhook } from "@/lib/crypto";
import { createHmac } from "node:crypto";

describe("VSCO normalization",()=>{it("preserves offset and assignments",()=>{const x=normalizeVscoEvent({id:12,name:"Wedding",start:"2026-08-12T15:00:00-06:00",timezone:"America/Denver",venue:{name:"Manor"},assignments:[{id:4,role:"Videographer",teamMember:{id:8,firstName:"A",lastName:"B",email:"a@example.com"}}]});expect(x.externalId).toBe("12");expect(x.startsAt.toISOString()).toBe("2026-08-12T21:00:00.000Z");expect(x.assignments?.[0].teamMember.id).toBe("8")});it("reports missing assignments as null",()=>expect(normalizeVscoEvent({id:"1",name:"W",start:"2026-08-12T15:00:00Z"}).assignments).toBeNull())});
describe("deterministic inbound",()=>{it.each([["CONFIRM","CONFIRM"],["yes!","CONFIRM"],["decline","DECLINE"],["STOP","STOP"],["MENU","HELP"],["show my assignment details","DETAILS"],["what ceremonies are upcoming?","SCHEDULE"],["where is my venue?","LOCATION"],["what time does it start?","HOURS"],["What is my rate?","PAY"],["PAY","PAY"],["show my invoice","FINANCIAL"],["What is next?","NATURAL_LANGUAGE"]])("%s", (text,intent)=>expect(deterministicIntent(text)).toBe(intent));it("blocks nonstandard financial questions",()=>{expect(isFinancialQuestion("When do I get paid?")).toBe(true);expect(isFinancialQuestion("Where is my ceremony?")).toBe(false)});it("calculates mileage from total trip miles",()=>{expect(standardPayReply("What is travel pay for 400 miles?")).toContain("$190.40");expect(standardPayReply("100 miles")).toContain("$0.00")})});
describe("quiet hours",()=>{it("detects night and moves to 8am",()=>{const night=new Date("2026-08-12T05:00:00Z");expect(outsideQuietHours(night,"America/Denver")).toBe(false);expect(nextAllowedTime(night,"America/Denver").toISOString()).toBe("2026-08-12T14:00:00.000Z")})});
describe("tokens and signatures",()=>{it("hashes opaque tokens",()=>{const x=createOpaqueToken();expect(x.token).not.toBe(x.hash);expect(sha256(x.token)).toBe(x.hash)});it("verifies HMAC without timing leaks",()=>{const raw="payload",key="secret",sig=createHmac("sha256",key).update(raw).digest("hex");expect(verifyHmac(raw,sig,key)).toBe(true);expect(verifyHmac(raw,"bad",key)).toBe(false)});it("verifies Quo's structured base64 signature and rejects replays",()=>{const now=Date.now(),timestamp=String(now),raw='{\n  "id": "EV1", "type": "message.received"\n}',compact=JSON.stringify(JSON.parse(raw)),key=Buffer.from("quo-secret").toString("base64"),digest=createHmac("sha256",Buffer.from(key,"base64")).update(`${timestamp}.${compact}`).digest("base64"),header=`hmac;1;${timestamp};${digest}`;expect(verifyQuoWebhook(raw,header,key,now)).toBe(true);expect(verifyQuoWebhook(raw,header,key,now+6*60*1000)).toBe(false)})});
